# Test jobs
qemu-alpine-arm64-test:
  stage: test
  image: registry.gitlab.com/lf-edge/runx/${CONTAINER}
  variables:
    CONTAINER: debian:unstable
    CC: gcc
  script:
    - ./automation/scripts/qemu-alpine-arm64.sh 2>&1 | tee qemu-smoke-arm64.log
  dependencies:
    - alpine-3.12-gcc-arm64
    - alpine-3.12-arm64-rootfs-export
    - kernel-5.10.30-arm64-export
    - u-boot-2021.07-arm64-export
    - xen-4.14-arm64-export
  artifacts:
    paths:
      - smoke.serial
      - '*.log'
    when: always
  tags:
    - x86
  except:
    - master
    - smoke
    - /^coverity-tested\/.*/
    - /^stable-.*/
